### ISSUE TITLE
[FEATURE] - Custom color schema

### ISSUE THREAD

**Issue by JanRuettinger** [golang-cz/devslog#12]
**Is your feature request related to a problem? Please describe.**
I'd like to set a custom color for the debug level.

**Describe the solution you'd like**
Ideally, I want to be able to pass an option to the handler which allows me to define a color for each log level.

**Comment by david-littlefarmer** [comment]
Good idea, I'll add it soon.

**Comment by david-littlefarmer** [comment]
I added this feature in PR #14. 
Also, I have released a new version, [v0.0.6](https://github.com/golang-cz/devslog/releases/tag/v0.0.6), which includes this feature.
