### ISSUE TITLE
[BUG] - slog.KindLogValuer is not handled

### ISSUE THREAD

**Issue by OrHayat** [golang-cz/devslog#20]
the log handler does not handle slog.KindLogValuer

simple code example

<pre>
type testStruct struct {
	A string
	B int
}

type lazyTestStruct testStruct

func (l lazyTestStruct) LogValue() slog.Value {
	panic("test panic during lazy evaluation of log value")
	return slog.Value{}
}

func TestExampleDevHandlerStdout(t *testing.T) {

	slogOpts := &slog.HandlerOptions{
		AddSource: true,
		Level:     slog.LevelDebug,
		ReplaceAttr: func(groups []string, a slog.Attr) slog.Attr {
			if a.Key == slog.TimeKey {
				return slog.Attr{}
			}
			return a
		},
	}

	opts := &devslog.Options{
		HandlerOptions:     slogOpts,
		MaxSlicePrintSize:  10,
		SortKeys:           true,
		NewLineAfterLog:    true,
		MaxErrorStackTrace: 0,
	}

	logger := slog.New(devslog.NewHandler(os.Stdout, opts))

	_testStruct := lazyTestStruct{}
	logger.Warn("expected_panic", "test", _testStruct)

	stdLibLogger := slog.New(slog.NewJSONHandler(os.Stdout, slogOpts))

	stdLibLogger.Warn("expected_panic", "test", _testStruct)

}

</pre>

**Expected behavior**
to have similar output to the one stdlib handler output (print error with some stack traces formatted)

**Comment by OrHayat** [comment]
@david-littlefarmer ur implemention is wrong since logValuer interface can return logValuer interafce too recursively
slog provide u  with Attr.Value.Resolve to handle this type
i opened pr u can look on it and merge it/cherry pick it to ur branch

**Comment by david-littlefarmer** [comment]
@OrHayat thank you for fix and tests!
I cherry picked your commit and it looks ok now.

**Comment by david-littlefarmer** [comment]
I merged your PR, so you are in contributors.
Sorry for confusion.
