### ISSUE TITLE
[BUG] - Keep indentation on multiline properties

### ISSUE THREAD

**Issue by matdurand** [golang-cz/devslog#23]
**Describe the bug**
Maybe in between a bug and a feature request, but when an attribute has a value with "\n", the result is hard to read.

**To Reproduce**

Here is an example:
This code:
```
logger.Info("dummy log", "attr1", "this is a long string\non multiple lines.\nit would read better if we kept indentation")
```
generates this log entry
```
[14:55:36]  INFO  dummy log
  attr1: this is a long string
on multiple lines.
it would read better if we kept indentation
```

**Expected behavior**
Ideally we should see:
```
[14:55:36]  INFO  dummy log
  attr1: this is a long string
         on multiple lines.
         it would read better if we kept indentation
```
or at the very least
```
[14:55:36]  INFO  dummy log
  attr1: this is a long string
  on multiple lines.
  it would read better if we kept indentation
```

**Comment by david-littlefarmer** [comment]
I created PR with this feature #24, please try it and let me know.
`go get github.com/golang-cz/devslog@string_indent`
I am not sure if it's ok to modify logged string, but at this point, i think it doesn't matter.

**Comment by matdurand** [comment]
The PR works fine. Thanks!

> I am not sure if it's ok to modify logged string, but at this point, i think it doesn't matter.

Maybe you could make it an config option?

**Comment by david-littlefarmer** [comment]
I added option `StringIndentation` for Config. PR is merged to master.
