### ISSUE TITLE
[BUG] - slog.Any does not handle interfaces

### ISSUE THREAD

**Issue by OrHayat** [golang-cz/devslog#26]
```
{
....
	g := map[any]any{"a": 2, 1: true}
	logger := slog.New(handler)
	logger.LogAttrs(context.Background(), slog.LevelError, "test", slog.Any("test", g))
}

```
output:
 ERROR  test
M test: 2 map[interface {}]interface {}
    1: Unknown type: interface
    a: Unknown type: interface

expected output:
 ERROR  test
M test: 2 map[interface {}]interface {}
    a: 2
    1:true

**Comment by david-littlefarmer** [comment]
@noppawitt resolved it in #27. Thank you.
