### ISSUE TITLE
[FEATURE] - Disable colors

### ISSUE THREAD

**Issue by gabyx** [golang-cz/devslog#38]
**Is your feature request related to a problem? Please describe.**
I want to disble color formatting, when I am on a terminal.
I want a settings `NoColor` which disables all color output, but keeps the everything else the same.
That is nice if we pipe stuff to a file.

**Describe the solution you'd like**
Add `NoColor` option.

**Describe alternatives you've considered**
-

**Comment by david-littlefarmer** [comment]
Here is PR #39 with changes using simple approach.
Is it enough?

**Comment by david-littlefarmer** [comment]
Merged, and released new version: https://github.com/golang-cz/devslog/releases/tag/v0.0.11
Because of rebasing i propagated bug to master and i released it before i noticed it :facepalm: , so use `v0.0.11`

**Comment by gabyx** [comment]
@david-littlefarmer : jeah realized it=)

**Comment by gabyx** [comment]
@david-littlefarmer : Thanks for the feature. Its very helpful!
